
# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run lint
      uses: vaibhav-jain/swagger-cli-action/@v2.6
      with:
        file_path: beacon-node-oapi.yaml

    - name: Bundle
      uses: mpetrunic/swagger-cli-action/@v1.0.0
      with:
        command: bundle -r -o beacon-node-oapi-bundle.yaml -t yaml beacon-node-oapi.yaml
